# Generated by Django 4.2.7 on 2023-11-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('cno', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=32)),
                ('tutor', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='sc',
            fields=[
                ('no', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('sno', models.CharField(max_length=32)),
                ('cno', models.CharField(max_length=32)),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('sno', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=16)),
                ('birth', models.CharField(max_length=16)),
                ('majority', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
    ]
